version: "3.8"

services:
  mysql:
    image: mysql:8.0 
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: app      
      MYSQL_USER: admin            
      MYSQL_PASSWORD: admin      
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adonis-app
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      TZ: UTC
      PORT: 3333
      HOST: 0.0.0.0
      LOG_LEVEL: info
      APP_KEY: PPBjDj2h3cwDfj93IZqDAs59q_YrMKez
      NODE_ENV: development
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin
      DB_DATABASE: app
    depends_on:
      - mysql
volumes:
  mysql_data: